//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVooraadBeheer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leverancier
    {
        public Leverancier()
        {
            this.ProductLeverancier = new HashSet<MagazineTitleLeverancier>();
            this.MagazineTransaction = new HashSet<MagazineTransaction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adresse { get; set; }
        public string PostCode { get; set; }
        public string City { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<MagazineTitleLeverancier> ProductLeverancier { get; set; }
        public virtual ICollection<MagazineTransaction> MagazineTransaction { get; set; }
    }
}
