//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVooraadBeheer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.MagazineTransactionFrom = new HashSet<MagazineTransaction>();
            this.MagazineTransactionTo = new HashSet<MagazineTransaction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adresse { get; set; }
        public string PostCode { get; set; }
        public string City { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<MagazineTransaction> MagazineTransactionFrom { get; set; }
        public virtual ICollection<MagazineTransaction> MagazineTransactionTo { get; set; }
        public virtual LocationMagazineTitleWarning LocationMagazineWarning { get; set; }
    }
}
