//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVooraadBeheer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagazineTitle
    {
        public MagazineTitle()
        {
            this.Magazine = new HashSet<Magazine>();
            this.MagazineSerieLeverancier = new HashSet<MagazineTitleLeverancier>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Language_Id { get; set; }
    
        public virtual ICollection<Magazine> Magazine { get; set; }
        public virtual ICollection<MagazineTitleLeverancier> MagazineSerieLeverancier { get; set; }
        public virtual LocationMagazineTitleWarning LocationMagazineTitleWarning { get; set; }
        public virtual Language LanguageSet { get; set; }
    }
}
