//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVooraadBeheer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MagazineTransaction
    {
        public int Id { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public System.DateTime DateTime { get; set; }
        public int Value { get; set; }
        public int MagazineId { get; set; }
        public Nullable<int> LeverancierId { get; set; }
        public Nullable<int> LocationFromId { get; set; }
        public Nullable<int> LocationToId { get; set; }
        public TransactionType TransactionType { get; set; }
    
        public virtual Location LocationFrom { get; set; }
        public virtual Location LocationTo { get; set; }
        public virtual Magazine Magazine { get; set; }
        public virtual Leverancier Leverancier { get; set; }
    }
}
