//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVooraadBeheer.Models
{
    using System;
    
    public enum TransactionType : int
    {
        Intern = 0,
        ShopToCustomer = 1,
        FromLeverancier = 2
    }
}
