//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCVooraadBeheer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VooraadModelsContainer : DbContext
    {
        public VooraadModelsContainer()
            : base("name=VooraadModelsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> LocationSet { get; set; }
        public virtual DbSet<Magazine> MagazineSet { get; set; }
        public virtual DbSet<MagazineTransaction> MagazineTransactionSet { get; set; }
        public virtual DbSet<Leverancier> LeverancierSet { get; set; }
        public virtual DbSet<MagazineTitleLeverancier> MagazineTitleLeverancierSet { get; set; }
        public virtual DbSet<MagazineTitle> MagazineTitleSet { get; set; }
        public virtual DbSet<Language> LanguageSet { get; set; }
        public virtual DbSet<LocationMagazineTitleWarning> LocationMagazineTitleWarningSet { get; set; }

        public System.Data.Entity.DbSet<MVCVooraadBeheer.Controllers.LocationWarningModelView> LocationWarningModelViews { get; set; }
    }
}
